### ISSUE TITLE
Zoom the camera out a bit more - want to see more of digit

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#106]

**Comment by Oraxien40** [comment]
with the latest push we can see down to the end of of digits tail
![Capture3](https://user-images.githubusercontent.com/82855401/142795789-0f20f233-465d-4386-bd3a-c16c58f6e618.PNG)

**Comment by MikelCodes** [comment]
Seems good to me, give a good angle of the world as well
