### ISSUE TITLE
Want to see a "stabilized" camera when we rotate or move the player

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#107]

**Comment by Oraxien40** [comment]
the camera now has a delayed smooth movement when the camera rotates.
This can be seen by looking at Dev level 1 in the scenes folder.

**Comment by Oraxien40** [comment]
Reopening because camera still has some bugs.

**Comment by Oraxien40** [comment]
player camera no longer randomly does a slow return to the dead zone, and is now ready to be reviewed.

**Comment by MikelCodes** [comment]
Feels and acts a lot smoother. This should be good for the project.
