### ISSUE TITLE
Adjust lighting - brighter environment

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#110]

**Comment by MaxCarlon** [comment]
Scene may look better with lower ceiling? @Oraxien40

**Comment by Oraxien40** [comment]
one note:

- The black camo textures on the isle assets cant be seen very clearly in the light.
![Capture9](https://user-images.githubusercontent.com/82855401/142942912-fd93ca9b-596f-4a28-a6a8-e50a804b1344.PNG)

**Comment by MaxCarlon** [comment]
Also need to fix "lighting seams"
