### ISSUE TITLE
Additional "props" to help the level feel less dry

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#112]
Lets start with creating a list of what these props are - pitch them to us.
Happy for you to start creating some of these after that.

**Comment by MaxCarlon** [comment]
Wall Signs - hanging or wall signs?
 - Dairy
 - Bread 
 - Produce
 - Deli
 -
![image](https://user-images.githubusercontent.com/92276880/142783436-3a0c04d5-0f80-4175-82f3-79f34e4fdaff.png)
![image](https://user-images.githubusercontent.com/92276880/142783457-cfaea2cc-bf95-40e2-9a72-a2d86b3ac953.png)
VS
![image](https://user-images.githubusercontent.com/92276880/142783481-6c4fb293-a6dd-46ac-9288-81b1534e713a.png)
![image](https://user-images.githubusercontent.com/92276880/142783526-11de6603-29a5-47b8-aaba-20c6bd047729.png)

**Comment by MaxCarlon** [comment]
![image](https://user-images.githubusercontent.com/92276880/142966268-6e3fed95-ac8a-4fe1-9b5f-f3010ab76512.png)
First pass on wall signs
