### ISSUE TITLE
waypoint marker text - change to show the ingredient that it represents

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#115]

**Comment by MikelCodes** [comment]
Works as it should

**Comment by Oraxien40** [comment]
waypoint apereas text when you get close to the explanation mark
![Capture15](https://user-images.githubusercontent.com/82855401/143972796-332f357e-fc04-400b-88d9-53c718f53462.PNG)
all seems good with this.
