### ISSUE TITLE
paper background behind the checklist

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#119]
Matilda to create the image - and bring into unity
Jordan to update the UI with this asset

**Comment by Oraxien40** [comment]
implemented into dev level 1 and ready to review.
![Capture10](https://user-images.githubusercontent.com/82855401/142949527-cdd3c424-5ee6-4052-9831-9387d20a081c.PNG)

**Comment by Oraxien40** [comment]
Matilda's Note:

- the text for the ingredients could be bigger
- the check box could be bigger

**Comment by tildakell** [comment]
Reviewed and Complete
