### ISSUE TITLE
Back button - transitions to "Main Menu"

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#127]

**Comment by Oraxien40** [comment]
When the back button was pressed it did not take me back to the main menu. 
The button stayed highlighted when it was pressed as an added note.
![Capture8](https://user-images.githubusercontent.com/82855401/142803979-8837be27-67c7-4d08-be28-1f1edf81a797.PNG)

**Comment by MikelCodes** [comment]
![LvlSelect1](https://user-images.githubusercontent.com/72060811/142976006-302bde8f-a4ac-409c-b4c6-2a3f1935ed4b.PNG)

**Comment by Oraxien40** [comment]
Back button now transitions back to the main menu screen.
