### ISSUE TITLE
Add "play" button under recipie pannel that switches to the selected scene

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#130]

**Comment by Oraxien40** [comment]
Couple things wrong with this:
1 - The background is stretched.
2 - The play button doesn't line up with the shadow behind it. 
3 - The back button should not be over the level select panel.

![Capture6](https://user-images.githubusercontent.com/82855401/142801713-596b6311-bceb-4c6b-a711-37bc2fe622ba.PNG)

**Comment by Oraxien40** [comment]
reopening because don't know why it was closed

**Comment by Oraxien40** [comment]
All previously mentioned problems have been addressed. 
Something that could be improved is the background of the recipe panel.
![Capture17](https://user-images.githubusercontent.com/82855401/143985030-21832788-b15b-4ef4-8d63-e48e93bf89e4.PNG)
