### ISSUE TITLE
[BUG] josh playing wrong animation.

### ISSUE THREAD

**Issue by Oraxien40** [AIESydneyStudents/DIGITAL_BASKET#140]
In dev level 2 josh stands in one spot, but instead of using his idle animation he is using his walking one
![Capture19](https://user-images.githubusercontent.com/82855401/144135491-059e104b-710f-48de-a580-7924417f0470.PNG)

**Comment by FlynnMay** [comment]
Fixed in: b772d14cfafb6491980756d25e1b3cb91c8a6ea1
