### ISSUE TITLE
Player : Mechanic : UI

### ISSUE THREAD

**Issue by Oraxien40** [AIESydneyStudents/DIGITAL_BASKET#76]
for more information about the Player UI look in the GDD under **User interface & controls**

**Comment by Oraxien40** [comment]
Mockup done

**Comment by Oraxien40** [comment]
UI implemented into Dev Level 1.
Feedback has been given to the in-game UI in issue #119

**Comment by tildakell** [comment]
Done

**Comment by Oraxien40** [comment]
no problems can be seen upon review
